# file: nginx/handlers/main.yml

- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes
  when: not nginx_first_start.changed and (nginx_managed_service is defined and nginx_managed_service == true)

- name: reload nginx
  service: name=nginx state=reloaded
  when: nginx_managed_service is defined and nginx_managed_service == true
  sudo: yes
